grails/todo/grails-app/domain/es/ua/expertojava/todo/Category.groovy
package es.ua.expertojava.todo

class Category {

    String name
    String description

    static hasMany = [todos:Todo]

    static constraints = {
        name(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
    }

    String toString(){
        name
    }
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Person.groovy
package es.ua.expertojava.todo

class Person {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		PersonRole.findAllByPerson(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/RequestMap.groovy
package es.ua.expertojava.todo

import org.springframework.http.HttpMethod

class RequestMap {

	String url
	String configAttribute
	HttpMethod httpMethod

	static mapping = {
		cache true
	}

	static constraints = {
		url blank: false, unique: 'httpMethod'
		configAttribute blank: false
		httpMethod nullable: true
	}
}

grails/todo/grails-app/domain/es/ua/expertojava/todo/Todo.groovy
package es.ua.expertojava.todo

class Todo {
    String title
    String description
    Date date
    Date reminderDate
    String url
    Boolean done=false

    Category category

    User user

    Date dateCreated
    Date lastUpdated

    Date dateDone

    static hasMany = [tags:Tag]
    static belongsTo = [Tag,User]

    static mapping = {
        autoTimestamp true
    }

    static searchable = true

    static constraints = {
        title(blank:false)
        description(blank:true, nullable:true, maxSize:1000)
        date(nullable:false)
        reminderDate(nullable:true, validator: {val, obj ->
            if(val && obj?.date){
                return val.before(obj.date)
            }
            return true
        })
        url(nullable:true, url:true)
        done(nullable:false, blank:false)
        category(nullable:true)
        dateDone(nullable:true)
        dateCreated(nullable: true)
        lastUpdated(nullable: true)
    }

    String toString(){
        title
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/CategoryController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import es.ua.expertojava.todo.*

@Transactional(readOnly = true)

class CategoryController {
    def springSecurityService
    def CategoryService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion index - Modelo []")
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryInstanceCount: Category.count()]
    }

    def show(Category categoryInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion show - Modelo []")
        respond categoryInstance
    }

    def create() {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion create - Modelo []")
        respond new es.ua.expertojava.todo.Category(params)
    }

    @Transactional
    def save(Category categoryInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion save - Modelo []")
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'create'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), /*categoryInstance.id*/ "'"+categoryInstance.name+"'"])
                redirect categoryInstance
            }
            '*' { respond categoryInstance, [status: CREATED] }
        }
    }

    def edit(Category categoryInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion edit - Modelo []")
        respond categoryInstance
    }

   // @Transactional
    def update(Category categoryInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion update - Modelo []")
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'edit'
            return
        }

        CategoryService.delete(categoryInstance)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect categoryInstance
            }
            '*'{ respond categoryInstance, [status: OK] }
        }
    }

   // @Transactional
    def deleteCategory(Category categoryInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Category - Accion deleteCategory - Modelo [${categoryInstance}]")

        if (categoryInstance == null) {
            notFound()
            return
        }

        categoryInstance.delete(flush:true)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/RequestMapController.groovy
package es.ua.expertojava.todo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RequestMapController {

    def springSecurityService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond RequestMap.list(params), model:[requestMapInstanceCount: RequestMap.count()]
    }

    def show(RequestMap requestMapInstance) {
        respond requestMapInstance
    }

    def create() {
        respond new RequestMap(params)
    }

    @Transactional
    def save(RequestMap requestMapInstance) {
        if (requestMapInstance == null) {
            notFound()
            return
        }

        if (requestMapInstance.hasErrors()) {
            respond requestMapInstance.errors, view:'create'
            return
        }

        requestMapInstance.save flush:true

        springSecurityService.clearCachedRequestmaps()

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'requestMap.label', default: 'RequestMap'), requestMapInstance.id])
                redirect requestMapInstance
            }
            '*' { respond requestMapInstance, [status: CREATED] }
        }
    }

    def edit(RequestMap requestMapInstance) {
        respond requestMapInstance
    }

    @Transactional
    def update(RequestMap requestMapInstance) {
        if (requestMapInstance == null) {
            notFound()
            return
        }

        if (requestMapInstance.hasErrors()) {
            respond requestMapInstance.errors, view:'edit'
            return
        }

        requestMapInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'RequestMap.label', default: 'RequestMap'), requestMapInstance.id])
                redirect requestMapInstance
            }
            '*'{ respond requestMapInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(RequestMap requestMapInstance) {

        if (requestMapInstance == null) {
            notFound()
            return
        }

        requestMapInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'RequestMap.label', default: 'RequestMap'), requestMapInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'requestMap.label', default: 'RequestMap'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/TagController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController {

    def springSecurityService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        //log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion index - Modelo []")
        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

    def show(Tag tagInstance) {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion show - Modelo []")
        if (tagInstance == null) {
            notFound()
            return
        }
        respond tagInstance
    }

    def create() {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion create - Modelo []")
        Tag tagInstance = new Tag(params)
        respond tagInstance
    }

    @Transactional
    def save(Tag tagInstance) {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion save - Modelo []")
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tag.label', default: 'Tag'), "'"+tagInstance.name +"'"])
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance) {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion edit - Modelo []")
        if (tagInstance == null) {
            notFound()
            return
        }
        respond tagInstance
    }

    @Transactional
    def update(Tag tagInstance) {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion update - Modelo []")
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Tag.label', default: 'Tag'),  "'"+tagInstance.name +"'"])
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK]}
        }
    }

    def deleteConfirm(Tag  tagInstance){
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion deleteConfirm - Modelo []")
        respond tagInstance
    }

    @Transactional
    def delete(Tag tagInstance) {
//        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador Tag - Accion delete - Modelo []")
        if (tagInstance == null) {
            notFound()
            return
        }

        tagInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/controllers/es/ua/expertojava/todo/UserController.groovy
package es.ua.expertojava.todo

import grails.plugin.springsecurity.annotation.Secured

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {
    def springSecurityService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    def index(Integer max) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion Index - Modelo []")
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion Show - Modelo []")
        respond userInstance
    }

    def create() {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion Create - Modelo []")
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion Save - Modelo []")
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion edit - Modelo []")
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion update - Modelo []")
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {
        log.trace("User ${springSecurityService.getCurrentUser()} - Controlador User - Accion delete - Modelo []")

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails/todo/grails-app/views/todo/_form.gsp
<%@ page import="es.ua.expertojava.todo.Todo" %>



<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'title', 'error')} required">
    <label for="title">
        <g:message code="todo.title.label" default="Title" />
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="title" required="" value="${todoInstance?.title}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'description', 'error')} ">
    <label for="description">
        <g:message code="todo.description.label" default="Description" />

    </label>
    <g:textArea name="description" cols="40" rows="5" maxlength="1000" value="${todoInstance?.description}"/>

</div>


<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'date', 'error')} required">
    <label for="date">
        <g:message code="todo.date.label" default="Date" />
        <span class="required-indicator">*</span>
    </label>
    <g:datePicker name="date" precision="day"  value="${todoInstance?.date}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'reminderDate', 'error')} ">
    <label for="reminderDate">
        <g:message code="todo.reminderDate.label" default="Reminder Date" />

    </label>
    <g:datePicker name="reminderDate" precision="day"  value="${todoInstance?.reminderDate}" default="none" noSelection="['': '']" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'done', 'error')} ">
    <label for="done">
        <g:message code="todo.done.label" default="Done" />

    </label>
    <g:checkBox name="done" value="${todoInstance?.done}" />

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'url', 'error')} ">
    <label for="url">
        <g:message code="todo.url.label" default="Url" />

    </label>
    <g:field type="url" name="url" value="${todoInstance?.url}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'category', 'error')} ">
    <label for="category">
        <g:message code="todo.category.label" default="Category" />

    </label>
    <g:select id="category" name="category.id" from="${es.ua.expertojava.todo.Category.list()}" optionKey="id" value="${todoInstance?.category?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

%{--<div class="fieldcontain ${hasErrors(bean: todoInstance, field: 'tags', 'error')} ">
    <label for="tags">
        <g:message code="todo.tags.label" default="Tags" />
    </label>
</div> --}%


<g:hiddenField name="user" required="" value="${sec.loggedInUserInfo(field:"id")}"/>

grails/todo/grails-app/views/todo/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: expertojava
  Date: 19/02/16
  Time: 15:23
--%>

<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <asset:stylesheet src="todo.css"/>
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>

</head>
<body>
<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
        <li><a class="list" href="${createLink(uri: '/todo/selectCategories')}">Selección de ategorías</a></li>
    </ul>
</div>
<div id="list-todo" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            <th>Edition</th>
            <g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />

            <g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />

            <g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />

            <g:sortableColumn property="done" title="${message(code: 'todo.done.label', default: 'Done')}" />
            %{--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--}%
            %{--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--}%

        </tr>
        </thead>
        <tbody>
        <g:each in="${todoInstanceList}" status="i" var="todoInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                <td>
                    <g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
                        <fieldset class="buttons">
                            <g:link class="edit" action="edit" resource="${todoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                            <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                        </fieldset>
                    </g:form>
                </td>
                <td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>

                <td><g:formatDate date="${todoInstance.date}" /></td>

                <td>${fieldValue(bean: todoInstance, field: "url")}</td>

                <!--Etiqueta todoTagLibrary que creamos con comando-->
                <td class="iconTodo"><todo:printIconFromBoolean value="${todoInstance.done}"/></td>

                %{--<td><g:formatBoolean boolean="${todoInstance.done}" /></td>--}%
                %{--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--}%
                %{--<td><g:formatDate date="${todoInstance.reminderDate}" /></td>--}%

            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${todoInstanceCount ?: 0}" />
    </div>
</div>
</body>
</html>

grails/todo/grails-app/views/todo/listByCategory.gsp
<%--
  Created by IntelliJ IDEA.
  User: expertojava
  Date: 19/02/16
  Time: 15:23
--%>
<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
        <li><a class="list" href="${createLink(uri: '/todo/selectCategories')}">Selección de ategorías</a></li>
    </ul>
</div>
<div id="list-todo" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            <g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />

            <g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />

            <th><g:message code="todo.category.label" default="Category" /></th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${todoInstanceList}" status="i" var="todoInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>

                <td><g:formatDate date="${todoInstance.date}" /></td>

                <td>${fieldValue(bean: todoInstance, field: "category")}</td>
            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${todoInstanceCount ?: 0}" />
    </div>
</div>
</body>
</html>

grails/todo/grails-app/views/todo/showTodosByUser.gsp
<%--
  Created by IntelliJ IDEA.
  User: expertojava
  Date: 19/02/16
  Time: 15:23
--%>

<%@ page import="es.ua.expertojava.todo.Todo" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <asset:stylesheet src="todo.css"/>
    <g:set var="entityName" value="${message(code: 'todo.label', default: 'Todo')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>

</head>
<body>
<a href="#list-todo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
    </ul>
</div>
<div id="list-todo" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>
            <th>Edition</th>
            <g:sortableColumn property="title" title="${message(code: 'todo.title.label', default: 'Title')}" />

            <g:sortableColumn property="date" title="${message(code: 'todo.date.label', default: 'Date')}" />

            <g:sortableColumn property="url" title="${message(code: 'todo.url.label', default: 'Url')}" />

            <g:sortableColumn property="done" title="${message(code: 'todo.done.label', default: 'Done')}" />
            %{--<g:sortableColumn property="description" title="${message(code: 'todo.description.label', default: 'Description')}" />--}%
            %{--<g:sortableColumn property="reminderDate" title="${message(code: 'todo.reminderDate.label', default: 'Reminder Date')}" />--}%

        </tr>
        </thead>
        <tbody>
        <g:each in="${todoInstanceList}" status="i" var="todoInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                <td>
                    <g:form url="[resource:todoInstance, action:'delete']" method="DELETE">
                        <fieldset class="buttons">
                            <g:link class="edit" action="edit" resource="${todoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                            <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                        </fieldset>
                    </g:form>
                </td>
                <td><g:link action="show" id="${todoInstance.id}">${fieldValue(bean: todoInstance, field: "title")}</g:link></td>

                <td><g:formatDate date="${todoInstance.date}" /></td>

                <td>${fieldValue(bean: todoInstance, field: "url")}</td>

                <!--Etiqueta todoTagLibrary que creamos con comando-->
                <td class="iconTodo"><todo:printIconFromBoolean value="${todoInstance.done}"/></td>

                %{--<td><g:formatBoolean boolean="${todoInstance.done}" /></td>--}%
                %{--<td>${fieldValue(bean: todoInstance, field: "description")}</td>--}%
                %{--<td><g:formatDate date="${todoInstance.reminderDate}" /></td>--}%

            </tr>
        </g:each>
        </tbody>
    </table>
    <div class="pagination">
        <g:paginate total="${todoInstanceCount ?: 0}" />
    </div>
</div>
</body>
</html>